### ISSUE TITLE
Allow skill spending actions that allow unclaimed to be used without the equivalent wallet skill 

### ISSUE THREAD

**Issue by Sellie96** [CryptoBlades/cryptoblades#1131]
Minting Characters requires wallet skill to be able to interact with it on the frontend.

**Comment by brian-man** [comment]
@Sellie96 
The following contract functions already support rewards (unclaimed skill):
- mintCharacter
- mintWeapon
- mintWeaponN
- burnWeapon
- burnWeapons
- reforgeWeapon
- reforgeWeaponWithDust

The same is true for the corresponding front end functions.

So I'm not sure what this issue is asking to be changed.

**Comment by Sellie96** [comment]
Had to double check apparently it's the mint character function that's blocked. Requires having any amount of normal skill to interact with it
