### ISSUE TITLE
skill shop

### ISSUE THREAD

**Issue by seiyria** [CryptoBlades/cryptoblades#119]
There should be a new shop tab that lets users buy items with skill. It should have some of these (balance pending):

- [x] a potion of rename (to rename a single character) for 10 skill (unlimited buys)
- [ ] a potion of experience gain (+10% XP for Y days for all characters) for Z skill (X / week)
- [ ] a potion of power that reduces the spread of enemy power from +/- 10 to +/- 5 for X skill (Y / week)
- [ ] a potion of weakness that reduces enemy power to 1 for a single fight for X skill (Y / week)
- [ ] ~~a potion of stamina to refill stamina for one character for X skill (Y / week)~~
- [ ] a potion of boosted strength (+10% power to all combats for X days) (Y / week)

All shop stuff should reset on probably friday nights.

We also want to be able to add stuff to shops on a biweekly basis, leaving the shop in two fridays. Some examples would be:

- [ ] rotating titles which apply to your wallet
- [ ] a limited time weapon, possibly a weak 5* or strong 4*, for X skill. ideally with a prefab construction so we can control the aesthetics
- [ ] limited time character cosmetics for X skill
- [ ] get a cosmetic for your character, such as a unique border (int on model, all done with css)

**Comment by Giovanny-DS** [comment]
a potion that changes the element of a character.

this would be useful for new. if were encouraging to grow our chars instead of creating an army of LVL 1 - 21 accounts. 

Usecases:

well to new starters, they can go all the way without having to buy in the market a higher prices chars of the same element. instead, they can recruit the four chars (which is cheaper) and **EARN** then they can turn all of the same elements at the same time they earn.

also if a player does need, (whatever the reason is) a high-level char of an element, they can change the element of that char without worrying about trading or selling it to buy another.

this will also provide a better game experience for those players who entered without that much knowledge and recruited their four chars. they can fix or adapt their team to any situation or weapon they have.

as an item that can be bought with skill. this will also help the economy getting the back skills to the contract. even if it's not used that much.

**Comment by brian-man** [comment]
> a potion of weakness that reduces enemy power to 1 for a single fight for X skill (Y / week)
Kind of weird to have an "I win" potion.

Will the payout be proportional to 1 monster power? :)

**Comment by brian-man** [comment]
> a potion that changes the element of a character.

Agree, a trait changer is simple to implement and doesn't unbalance the game.  With the right price it could be a huge skill sink prior to raids.

**Comment by seiyria** [comment]
I agree about trait changer. There should be one per element, though, to lower the UI load.

**Comment by poshdan** [comment]
I see a lot of fight related ideas here so I must warn that **any changes would need to have extremely low gas impact**.

Let's say a thousand users buy a week long potion for $50 that adds 1 cent to the gas cost. We gain $50k on potions and lose $350k on gas offset from the entire userbase doing fights. It's really difficult to balance this in our favor and I don't want guesswork in our economy.

Ideally, these potions would have to be implemented in a way that distributes the load.
For example, stamina potions restore outside of fights, so the fight code isn't affected.

**Comment by Joedel-Tera** [comment]
Hello devs i would like to add some portion to this one. Is it possible to add like some kind of a Tome or scroll? that gives to characters like a duration?

For instance 
Tome of Exp ( Adding Exp to Character ) To level Up or maybe additional Exp per fights???
Tome of Power ( Adding Pwr to a character Duration of time )
Tome of Knowledge ( Adding Int to a character Duration of time )
Tome of Agility ???

Some thing like this.

**Comment by Nyawmeowww** [comment]
while we value inputs from players. Please refrain from posting here and post it on cryptoblades.hellonext.co

**Comment by antav7s** [comment]
Some stuffs for PvP fights in future would be great as well 😀.
Thanks for your effort CB team 💪🏻
