### ISSUE TITLE
Upgrading wax Bridge to Support ERC20 Token

### ISSUE THREAD

**Issue by MrBaptista69** [CryptoBlades/cryptoblades#1190]
Upgrade it so we can collect all fees poly is generating So we will not have to wait on connection when we eventually support more chains

**Comment by bilbolPrime** [comment]
Skimmed through the code and I believe the ideal approach is to a deploy an instance per chain because unlike the NFT bridge, there is no need for inter-chain communication.

Some changes will still be needed as the bridge is hardwired to BNB.

What's still common though is the database holding the history of transactions. An extra param should be added to show to which chain made the transaction. Also we need to check the APIs to make sure they support what we need.

Will add more info as I dig deeper in the code

**Comment by bilbolPrime** [comment]
Looking more at the bot, it seems we may have an issue with the growth rate of the chain and the way we save last processed block.
We only save it when we process some transaction => we may end up reprocessing "empty blocks" if we restart.

In theory it's possible to be stuck in a perma loop if too many "empty blocks" are in sequence. A simple solution to that is to save the latest read block to a database and use it instead of the last modified block on the chain.

Also with the testnet bot I am seeing a rate of 50 processed blocks per second which means an average of 5 blocks per second. Not sure if that's sufficient to ensure a stable up to date bot.

**Comment by bilbolPrime** [comment]
Update the API to store the last block
https://github.com/CryptoBlades/cryptoblades-api/issues/77

**Comment by bilbolPrime** [comment]
The bridge being stuck has been resolved (on testnet).
Created multiple issues on the waxbridgerepo to accomplish this issue.

Perhaps it's best to close this issue here and we'll log all details on the other repo @MrBaptista69 ?
