### ISSUE TITLE
Cryptoblades Character Titles Feature

### ISSUE THREAD

**Issue by Sellie96** [CryptoBlades/cryptoblades#1418]
Cryptoblades Title Feature

- Title equippable to characters on the wallet (E.g The Powerful Sellie, Levitate The Stinky) as both prefix or suffix.

- Titles want to be given out in a multitude of ways, quests,  streams , collection , event driven.

- There will a range of Titles to unlock so an interface to display both unlocked and locked Titles with a goal to collect them all and equip and swap between unlocked at will.

- Titles are visible on characters at all times.

- Titles are not transferable in any way they want to be earned personally.

- Titles are displayed in multiplayer scenarios such as pvp for bragging rights.

Birthday weekend is next week and requires a mock solution: Details TBD

Titles wanted initially and collected from;

Title 1 - PvP Livestream: Gladiator

Title 2 - Secret Livestream: Accumulator

Title 3 - Anniversary Livestream: First Year Earner

**Comment by poshdan** [comment]
Example contract mockup (incomplete)

Storing titles in pure string, can be arbitrarily given as one-off things, user can pick an active one from the unlocked array.
We'd use a bot to verify validity of requests. We can lookup events from past transactions to verify things like "fought during this hour" etc. Admin can also whitelist a title during an event with a simple call (ie setfreetitle function), and then turn it off after.

Frontend would read the selectedTitle variable to display for the given NFT.
Concerns with NFT bridge. We could have the user re-request on the new chain BUT it's a bit tricky to transfer titles since the new ID will be different. But something that a bot can look up to an extent.

`mapping(nfttype => ID/wallet => string[]) unlockedTitles (nfttype 0 can be wallet type)
mapping(nfttype => ID/wallet => string) selectedTitle
mapping(nfttype => titleID => bool) requestableTitles
mapping(nfttype => titleID => string) titleIDstrings
mapping(nfttype => string => bool) freeTitles
request[] requests
lastProcessedRequest

struct request {
int titleID
int nfttype
int wallet/nftID
}

selectTitle(nfttype, id, titleindex) {
	selectedTitle[nfttype, id] = unlockedTitles[nfttype, id, titleindex]
}

setFreeTitle(nfttype, bool) {
	freeTitles[nfttype] = bool
}

requestTitle(nfttype, titleID, nftID) {
	if(requestableTitle[nfttype, titleID])
		requests.push(titleID,nfttype,nftID) // make sure you cant double request tho
}

processTitleRequests() {
	for(int i = lastProcessedRequest; i < requests.length; i++) {
		assign title etc
	}
}
`
