### ISSUE TITLE
User onboarding on SKALE

### ISSUE THREAD

**Issue by kcper** [CryptoBlades/cryptoblades#1510]
To start playing on SKALE users need to get some gas first. We have a faucet create for that matter in our discord, bot-commands channel (https://discord.com/channels/833038505626173481/833235142046384129).

We need to create a banner / note on SKALE chain if user has no gas and direct them to our discord where they can request SFUEL from the faucet.

Command is /sfuel 0x...

**Comment by Sellie96** [comment]
I mentioned this in discord but to keep it with the issue. Having discord should absolutely not be a requirement this same feature can also be linked to the FE and distributed there.

**Comment by MrBaptista69** [comment]
No FE development will take place for this one. This will be done for Discord and not for the FE

**Comment by Sellie96** [comment]
Doing it as a discord bot was the absolute worst decision possible

**Comment by MrBaptista69** [comment]
at least for now,there is going to be no FE.

**Comment by Sellie96** [comment]
There absolutely is. I'll do it myself. There is absolutely no way you can justify not doing this, stopping a large amount of our playerbase from using the chain over an hours work nobody had thought of because once again it's an unspecced feature.

**Comment by seiyria** [comment]
@MrBaptista69 please provide a reason other than "we are not doing this" - what is the rationale? who said not to do it? why would we not make it better for users? this is a really user-hostile approach and doesn't help the fact that we gate entirely too many things behind discord as-is. I see no reason we shouldn't do this.

**Comment by seiyria** [comment]
Gating features behind Discord puts us in the same situation that gating our FAQ and our support and our everything else does. We should endeavour to move things out of Discord, not lock more things in it. It also doesn't increase engagement, it's an artificial barrier, and it is user-hostile, intentionally or otherwise. It also doesn't benefit us at all to just have random people that don't interact with us, and their only purpose is to claim gas.

This is just a categorically bad idea.

**Comment by Sellie96** [comment]
We need to make an app that players love. They enjoy. They have a great experience on. That's how we get communication. Not making the app hard to use intentionally. When we know how to fix it.

**Comment by Sellie96** [comment]
There is absolutely so much wrong with what you just said. I cannot believe I actually have to fight for this, I cannot believe people have approved an action that intentionally stops people playing Cryptoblades. I am astounded. This Skale release is already not going to be smooth the company has advertised all this hype for Skale. When in fact new players can't even play the chain due to no dex it's the extra bridge way or nothing, those who want to move are forced to give up their wallet addresses to the public, they are forced to make exhausting actions copy and pasting over and over again. Nobody will introduce their families or friends to Skale. 

A forced action will not make people engage we have tried it before and it ended with people leaving. I am not here arguing the matter because I enjoy it. I'm doing it because I'm actively passionate about the project and what you will drive away because of this will not be made up by this small amount of engagement you think will come, You want people to come? You want investors to see an active community? Stop actively fighting the community. The rewards need to not be empty for a month at a time because nobody knows who fills them, the app needs to be healthy, their actually needs to be a CB development team. Hell even the socials aren't in the application for people to join nor have they ever been? We are in an obsolute mess right now. We are losing the communities trust and support day by day. We cannot keep making decisions that negatively effect our playerbase. Talk to Levi about how the community will feel about this.

I'm absolutely exhausted from decisions been made without any tech guidance, I absolutely do not get paid enough to stop voicing my opinions and passion on the project and if you really want to silence me with "Because we said so" without any reason at all. You're fast going to drive away your development team too.
