### ISSUE TITLE
cannot use claim pool to pay with skill if wallet doesn't have the required amount

### ISSUE THREAD

**Issue by poshdan** [CryptoBlades/cryptoblades#16]

**Comment by brian-man** [comment]
@Nyawmeowww 
The "commit that referenced this issue" appears to be PVP-related and I don't see the reference.  Maybe github is confused because tehy both are number 16?  Weird.

@poshdan Can you elaborate on _where_ the pay cannot happen (but should)? Assuming the proposed change[s] aren't obsolete.

**Comment by Nyawmeowww** [comment]
Yah it did clash with another forked repo
