### ISSUE TITLE
[Feature] COMBAT error message

### ISSUE THREAD

**Issue by MrBaptista69** [CryptoBlades/cryptoblades#1754]
### Prerequisites

- [X] I checked to make sure that this feature has not already been filed
- [X] I'm reporting this information to the correct repository
- [X] I understand enough about this issue to complete a comprehensive document

### Describe the feature and its requirements

A user was getting an error message when trying to do combat. When trying to do a combat when a character and/or weapon is in the pvp arena. Currently the error message is not clear to the user. All of the below warnings, should be warnings from the front end, with the corresponding buttons disabled and the warning shown next to the button or on hover next to a warning icon !

1. If they are trying to use a character for combat that is already in the PvP arena

2. If they are trying to use a weapon for combat that is already in the PvP arena

3. If they are trying to use both a character and weapon that is already in the PvP arena

4. If they are trying to use a character for combat that is already in a raid

5. If they are trying to use a weapon for combat that is already in a raid

6. If they are trying to use both a character and weapon that is already in a raid

### Is your feature request related to an existing issue? Please describe.

Nope

### Is there anything stopping this feature being completed?

Nope

### Describe alternatives you've considered

None

**Comment by poshdan** [comment]
This error has been solved since the following commit:
https://github.com/CryptoBlades/cryptoblades/commit/76cba37feb53439bdc7c06712b465a62285e8655

BTW, being in raid has never prevented further action from the character/weapon. It would have only prevented fighting because raid normally drains stamina and durability. The frontend does not update those values after joining raid, but it will update on its own in a few minutes (or by clicking the character again).

Also, this will be irrelevant once Equipment Manager arrives (and there should instead be warnings asking to equip things).
