### ISSUE TITLE
raids v1

### ISSUE THREAD

**Issue by seiyria** [CryptoBlades/cryptoblades#213]
- [ ] 8 hour window to join a raid, early  joiners have better chance at good loot. no withdraw once committed
    - weighted random chance based on join time for good loot, the earlier the better. maybe on an exponential curve if needed to encourage joining
- [ ] 16 hour locking of all NFT deposit/withdraws while the raid 'executes' 
    - add locked time + raid duration to character staminaTimestamp when character submitted. Character will finish raid with as much stamina as it joined with.
- [ ] raid requires 1 character and 1 weapon to be sent and locked until complete
- [ ] cost 10 USD worth of skill to join a raid

LOOT!
- [ ] raids reward XP to everyone, but not as much as if they spent 16 hours fighting
- [ ] raids increment a 'raids completed' stat on the character NFT
- [ ] raids reward 1-5* trash (for reforging) randomly to most but not all players - Seiyria's Pet Rock, Kroge's Toothpick, KR's Hammer, Dan's Abacus, a normal rock, broken weapons, whatever - bottom line is that they're still useful for reforging. they should roll no stats and no trait (pwr)
- [ ] raids reward "rare items that are mysterious in nature and can be given a purpose down the line" (trinkets)
  - 1 per raid
- [ ] raids could reward 1-5* swords
- [ ] raids could reward dust (if it gets merged)
- [ ] raids could reward keys (for yet tbd content) (could use trinkets)
- [ ] each raid reward should have a common and rare variety, with a drop chance to get each upon completion
  - star levels for trinkets
- [ ] raids should reward at most 2 of the rewards above so you can't get everything in one go
- [ ] raid rewards scale based on your contributed power, the strong you are the better your loot for carrying the team
- [ ] you can send 0-4 characters on a raid
- [ ] raids should have a chance of failure, potentially: roll(-raidpower, +ourpower) and if the number is negative the raid is lost, positive is won
- [ ] raid boss power is pre-determined before starting
- [ ] raids is not limited to number of players; the more there are the better the odds

TRINKETS:

- [ ] trinkets should have an entry fee to get. every .1 skill (TBD) added to the pot is another entry into the "raffle" to get a trinket.
- [ ] trinkets should be able to be burned to attach them to characters or weapons
- [ ] trinket of counting battle data - with this equipped, your character NFT will count battle wins and losses for hero score calculations (#340)
- [ ] trinket of less stamina - reduces stamina cost by 25%
- [ ] trinket of bonus xp - gives bonus XP to the character with this effect
- [ ] trinket of boosted element X damage (need one for each element, boost power by Y%)

**Comment by crypto-smoke** [comment]
My ideas for raids. I wanted to combine them with your initial issue but the ability to do so eludes me right now. 

- 8 hour window to join a raid, to cross timezones for all players
- Cost skill to enter
- Character must have full stamina to join (or full stamina by raid start time) (but we should keep things simple)
- 16 hour lock during the raid
- Characters returned with zero stamina

- Raids are not limited by number of players
- They COULD be limited by accumatled power (but perhaps not initially)
- Raid boss power is determined by players combined power and then rolled +/- 10% or whatever, like fights now
- Make raids harder to drop better loot by adjust min/max boss roll

- All raiders get XP but not as much as if they had fought for the 16 hours
- Some loot is distributed to everyone 
	- raids completed stat increased in character NFT to increase NFT uniqueness/value. 
	- seperate stats for entered raids and won raids maybe?
- Rare loot is dropped randomly to some players 
	- swords?
- Epic loot is dropped by weighted random chance based on power, to entice high level characters to join 
	- TBD NFTs
- Raids should NOT reward SKILL. Keep that to regular fights or players may favor one system over the other
- People who lock in early should have a higher drop chance than those who lock in later, high risk, high reward. Early and late are defined by 15 minute brackets of time until the raid starts.
	- Could do this with weighted random based on time joined, no need for 15 minute windows

**Comment by crypto-smoke** [comment]
I think this is about where we are now: 

- [ ] 8 hour window to join a raid, early  joiners have better chance at good loot. no withdraw once committed
	- weighted random chance based on join time for good loot, the earlier the better. maybe on an exponential curve if needed to encourage joining
- [ ] 16 hour locking of all NFT deposit/withdraws, then characters can be claimed with zero stamina
	- set staminaTimestamp to raid end time upon deposit of character to raid contract
- [ ] raid requires 1 character and 1 weapon to be sent and locked until complete
- [ ] cost 10 USD worth of skill to join a raid


LOOT!
- [ ] raids *should* reward XP to everyone, but not as much as if they spent 16 hours fighting
- [ ] raids *should* increment a 'raids completed' stat on the character NFT
- [ ] raids could reward 1-5* trash (for reforging) - Seiyria's Pet Rock, Kroge's Toothpick, KR's Hammer, Dan's Abacus, a normal rock, broken weapons, whatever - bottom line is that they're still useful for reforging. they should roll no stats and no trait (pwr)
- [ ] raids could reward "rare items that are mysterious in nature and can be given a purpose down the line" (keys)
- [ ] raids could reward 1-5* swords
- [ ] raids could reward keys (for yet tbd content)
- [ ] each raid reward should have a common and rare variety, with a drop chance to get each upon completion
- [ ] raids should reward at most 2 of the rewards above so you can't get everything in one go

- [ ] you can send 0-4 characters on a raid
- [ ] raids should have a chance of failure, potentially: roll(-raidpower, +ourpower) and if the number is negative the raid is lost, positive is won
	- smoke proposed to keep the combat mechanic as close to the existing one as possible. Limit the bosses minimum roll to increase chance of raid failing
- [ ] raids should have a varying number of slots (at least 100 max, but ranging from 100 to 300, maybe?)
	- perhaps not limited by slots but by total power of the raid party

**Comment by crypto-smoke** [comment]
Potential raid trinket buffs, courtesy of Groshmak: 
- Increase XP Gain by xy%
- Increase Combat earnings by x skill/xy%
- Decrease overall enemy strength by x power/xy%
- Increase stamina regeneration by x/xy%
- Increase max stamina by x/xy%
- Bless your weapon with faith X  (similar to LB reforging)
- Decrease reforging cost by x/xy%
- Decrease forging cost by  x/xy%
- Decrease strength of weak element against your character x/xy% (Power 1960 Earnings|(-70)|1890
- Decrease strength of element, strong against your character
- Increase Character slots by X
- Increase Raid Power

**Comment by seiyria** [comment]
shortlist of trinket buffs that will work for us:

- xp gain (+1% per level, cap of 100)
- decreasing enemy strength (-0.5% per level, cap of 100)
- stamina cap increase (+1 per level)
- decrease weak element debuff (-0.1% per level, cap of 100)
- increase strong element buff (+0.1% per level, cap of 100)
- raid-only power boost (unlimited, maybe +1 power per level in raids only)

**Comment by seiyria** [comment]
only one trinket drops per raid, to a random raid member, and it's an NFT that can go on the market

**Comment by crypto-smoke** [comment]
- [ ] 8 hour window to join a raid, early  joiners have better chance at good loot. no withdraw once committed
    - weighted random chance based on join time for good loot, the earlier the better. maybe on an exponential curve if needed to encourage joining
- [ ] 16 hour locking of all NFT deposit/withdraws while the raid 'executes' 
    - add locked time + raid duration to character staminaTimestamp when character submitted. Character will finish raid with as much stamina as it joined with.
- [ ] raid requires 1 character and 1 weapon to be sent and locked until complete
- [ ] cost 10 USD worth of skill to join a raid

LOOT!
- [ ] raids reward XP to everyone, but not as much as if they spent 16 hours fighting
- [ ] raids increment a 'raids completed' stat on the character NFT
- [ ] raids reward 1-5* trash (for reforging) randomly to most but not all players - Seiyria's Pet Rock, Kroge's Toothpick, KR's Hammer, Dan's Abacus, a normal rock, broken weapons, whatever - bottom line is that they're still useful for reforging. they should roll no stats and no trait (pwr)
- [ ] raids reward "rare items that are mysterious in nature and can be given a purpose down the line" (trinkets)
  - 1 per raid
- [ ] raids could reward 1-5* swords
- [ ] raids could reward keys (for yet tbd content) (could use trinkets)
- [ ] each raid reward should have a common and rare variety, with a drop chance to get each upon completion
  - star levels for trinkets
- [ ] raids should reward at most 2 of the rewards above so you can't get everything in one go
- [ ] raid rewards scale based on your contributed power, the strong you are the better your loot for carrying the team

- [ ] you can send 0-4 characters on a raid
- [ ] raids should have a chance of failure, potentially: roll(-raidpower, +ourpower) and if the number is negative the raid is lost, positive is won
- [ ] raid boss power is pre-determined before starting
- [ ] raids is not limited to number of players; the more there are the better the odds

**Comment by poshdan** [comment]
Started a branch called "raids".
NFT rewards created but not implemented yet (key lootbox, junk, trinket)

**Comment by poshdan** [comment]
Some questions:

-Is the "lockout" of 16 hours meant to use the stamina system or some other type of cooldown? Weapons are scheduled to have durability soon, which would make this a convenient way to handle it for both.
-Not sure how we can make the raid boss power be fair and meaningful by pre-determining it before the raid starts... it's hard to anticipate the amount of power players will dedicate every time, the most we could do is use power data from previous raids. (and account for timezone variations) I'm open to suggestions on how to do the raid power, else I think we could just do the +/- 10% roll based on the player power sum on completion. Perhaps we can predetermine a +/- 10% percentage offset, determining the difficulty of the raid, and giving us a vector on rewards?
-Any figures on how much difference there should be between someone joining early vs late? Does it even make sense if we drop the predetermined boss power aspect?

And some notes on implementation:

We need to distribute the gas load. We need to make sure reward seed manipulation is not possible (our function call to resolve the raid must submit a safe random seed that in turn determines users rewards).
The rewards should be made claimable using that seed with a version number so we can be backwards compatible for those who do not claim until much later. (exception can be the ultra rares like the 1-per-raid trinket drop, we can do that immediately, since it helps us know in advance who the lucky winner is)

Does anyone have an idea on how we can distribute a fair share of the rewards without calculating/storing a seed per-user, and without giving them the ability to manipulate the reward?
Ideally, their reward should be a derivative of the resolution seed using their wallet or nft ID, but I'm not sure how we can ensure distribution percentages that way.

**Comment by seiyria** [comment]
- the lockout will use the stamina system. Basically, it'll push forward the stamina timestamp by 16 hours. weapons should have this same setup
- we're going to have to guess. this also depends on what system we choose. if we go with my roll(-monster,+player) solution we don't really _need_ to pick high, because they'll always have a fair chance of winning. if we go with the other %-based solution then it doesn't really make sense to pick a power anyway. If we do go with the first one, we can yolo a power based on slots, maybe 200 per slot, as most players will have significantly higher than that, but if it's 100 slots, then that's 20k the boss has, vs whatever the players have. of course, that can scale up too if we want a harder encounter
- it makes sense no matter what. drop rates are tied to how soon you join. early joiners would see a +10% chance to get a rare version of whatever the drops are, scaling down to 0% after probably 2 or 4 hours (so if you join between 4 and 8 hours late, it's 0%)

what I would do is, instead of storing per raid, keep track of all historical raids (if possible), or at least keep them for a week. if they vanish for a week, then they can't claim on that raid. after a week, cycle it out and remove the option to claim from it.

**Comment by poshdan** [comment]
Contract work is mostly complete and pushed to the "raids" branch.
Just needs the NFT rewards implemented (their contracts are created (not fully implemented) but they need to be pulled in and called to mint), a basic algo of distribution has been laid out. (dust is excluded for now)

Xp scales with the early join bonus, and is given for lost raids too.
Raiders are stored in an array, the length of which is then used to calculate the early join bonus (up to midpoint) rather than a timestamp solution (it seemed more practical but I'm open to hearing arguments for timestamps)
All raid data is historically kept and never cleaned out, since the gas refund from clearing does not outweigh the benefit of keeping a history. (imo)

Operating costs are minimal, reward claim is gas-heavy but remains to be measured.
Rewards are claimed using a seed derivative that is picked in a safe way the moment the raid concludes, so no manipulation is possible.

Distribution of rewards is based on two rolls: a common drop roll and a rare drop roll, both of which are multiplied based on the character's relative contribution (and join bonus) compared to the average. Almost everyone will get a common drop, and everyone has a shot at a rare drop however, to have any reasonable chance, you need to be above the average.
Will likely need tweaking but most of all need a proper simulation for expected economic impact.

**Comment by poshdan** [comment]
Contracts are good to go as far as I'm concerned, pending balancing changes.
A bot will have to call doRaid() on a schedule to operate the raid, and that's about it.

Tasks for frontend:

-tell player it costs skill to join
-confirmation popup on joining raid with the entry fee and the stamina / durability costs.
-remove the "bounty" text, we do not pay out skill for this
-add text that says "joining early gives you up to 10% bonus in power"
-add text that says "rewards are based on your contributed power compared to others"
-add images of possible drops: weapon, (dust?), and two secret drop icons (a faded square with a question mark)
-update "raid title" to "Dragon's lair"
-update "raid name" to show some dragon name from a hardcoded list, choose one using modulo with raid index

Contract functions to hook in on frontend:
joinRaid(characterID, weaponID)
raidIndex()
getRaidEndTime(raidIndex)
getRaidParticipantCount(raidIndex)
xpReward()
staminaCost()
durabilityCost()
getJoinCostInSkill()
getRaidStatus(raidIndex) // 0 = UNSTARTED, 1 = STARTED, 2 = WON, 3 = LOST, 4 = PAUSED
getRaidBossPower(raidIndex)
getRaidBossTrait(raidIndex)
getEligibleRewardIndexes(startIndex, endIndex) // to check whether previous raids had eligible rewards)
isEligibleForReward(raidIndex)
getParticipatingCharacters()
getParticipatingWeapons()
canJoinRaid(characterID, weaponID)

**Comment by poshdan** [comment]
This ticket is super open for frontend work for anyone willing to take it. I have just pushed another update that hooks in the data read from the contract. Just need to fix the layouts, add a popup confirmation maybe, and format some strings! (some images for the drops would be nice too)

**Comment by seiyria** [comment]
https://github.com/CryptoBlades/cryptoblades/issues/214 closing this, v2 is open and should be commented on from now on
