### ISSUE TITLE
highlight current account/characters on leaderboard

### ISSUE THREAD

**Issue by seiyria** [CryptoBlades/cryptoblades#242]
probably put a star next to the name on the left

**Comment by teroneko** [comment]
Is this a good first issue? I want to become familiar with smart contracts. :)

**Comment by seiyria** [comment]
@teroneko This issue is actually entirely frontend. I don't think we have any "easy" smart contract issues at the moment. 

Issues are allowed to be taken as long as they're not assigned, though.

**Comment by teroneko** [comment]
I would like to help. I just need to look over the code to match the address of current wallet and the possible matching address in leaderboard to highlight it. So if permitted I would setup the repo to run it local. :)

**Comment by seiyria** [comment]
We also will want the characters to match up.

You're welcome to get it up and running. After that, I can assign it to you if you're all good to go.

**Comment by teroneko** [comment]
Okay. I think I am ready. Here some thoughts about the feature implementation.

1. The leaderboard API is not returning the character ID alone (in case of characters) but it is instead included in the name. Can this be changed? An idea would be to create a custom data type for each leaderboard id (0 -> characters that includes `name`, `value` and *NEW*, the `characterId`)
2. The data of characters (via ownCharacters (via getter)) and leaderboard via API must be linked together.
3. Therefore the API call can be moved to reducer (dispatch action to store) and link characters (and wallet id) with leaderboard data or
4. quick and dirty in the created method. But that would not be wisely because of the problably distinction of leaderboard ids and the addtional data they may have or can get in future and therefore can lead to different views. Of course we could generalize the highlighting by adding a boolean to each "leader board object" and decide on leader board id when to turn on the highlight.

In my work I got very sensitized to make something very clear and understandable and only a star is not very clear and understandable.
Here an example. To highlight a row it is bordered black and the star is highlighting that you overhaul more than 3 players in this leage:
![Unknown](https://user-images.githubusercontent.com/6233221/125365766-25376c00-e375-11eb-9c3b-c6fc8700117e.png)

**Comment by seiyria** [comment]
1. The API can be changed, although the only difference here is it's an O(N^2) instead of O(N) because you'd have to iterate over all the characters, do a .includes, etc. I'm admittedly not sure this is super necessary but I can do it if really desired.
2. There isn't anything in the API that knows what character belongs to what user.
3. Sure, anything is fine.
4. API is a static route here, no data returned but what you see. It has no idea who's requesting.

Also, in that example, a star isn't great because it blends in with the background. In our case, a star would be sufficient as the interface isn't very busy.

**Comment by teroneko** [comment]
Okay, it is hard to understand you. With API call is meant the call to get the leaderboard. There is the character id not present as atomic information. I would need it. So is this achievable to add it when fetching https://cryptoblades-api.herokuapp.com/static/leaderboard?

Regarding 1., I am not sure what you mean. In the store you would simply tranform each leaderboard object into a new object with additional information. In this case whether highlighted or not. You would iterate over each leaderboard item and check if id matches one id of own character IDs (or wallet id) an if so, just add true to `isOwned`. The character object itself is not in need of the information whether it is in the leaderboard or not. :D

**Comment by seiyria** [comment]
I get what you mean, but I don't think it needs to be added to the leaderboard, as said. You can do `myCharNames.some(myCharName => checkLeaderboardName.includes(myCharName))` to get whether or not it's there. As stated, I _can_ add the character id though.

These can be handled in the store or wherever needed.

**Comment by teroneko** [comment]
Mhh. Are we talking about the same? I mean vue store. Is it not appropiate to separate UI from logic? So you would need to put every API call that changes the state of the store in the reducer of the store. So you dispatch the "leaderboard fetch" inside component. after fetch you dispatch update. The update would have access to leaderboard and then you attach the info whether it is highlighted or not (in case of characters get characters via `dispatch('ownCharacters')`, compare via character id and set `isOwned`). Then the state of store gets udpated and immediatelly the vue dom gets updated and the rows by `:key="entry.name"` get highlighted or not.

The problem: I would have to extract the id from the name. that is not very good in programmer view. But for a quick and temporary solution it would suffice to just check if character id is ".include"d in the name of an leaderboard entry.

*I think I just assume that it would completely normal, always separate API call from UI and move everything to store (and there reducer).*

**Comment by teroneko** [comment]
Ahh I see. Mhh.. Okay. I will look what I can do. :)

Well, adding the character id to leaderboard entry would just be right, because `name` is just the human presentation of data. it is not perfomancewise to check via ".include" or rely on the name to not change. I mean it is verly unlikely that the name won't contain the character ID anymore but what when you allow to name characters manually in the future? :D The name could contain another character id as name or whatever. but the `characterId` would remain the same.

Mhh. another thing: Ganache and the CryptoBlades frontend is running. I also connected via MetaMask. How I can make the frontend functional? I think I need SKILL to surpass the the welcome message?

**Comment by seiyria** [comment]
I've added character id to the payload so that can be used.

Also, I'm not sure where you're stuck but your best bet is asking in the round table discord chat. We can help more there.

**Comment by teroneko** [comment]
Because of reasons, I cannot push my results. Good luck.
