### ISSUE TITLE
Using purchaseListing with unclaimed Skill doesn't work

### ISSUE THREAD

**Issue by brian-man** [CryptoBlades/cryptoblades#282]
Repro steps:
1. Create account
2. Create character
3. Fight until you have some unclaimed Skill
4. Remove all Skill tokens from account
5. Use market to purchase an NFT for <- your unclaimed Skill balance
PROBLEM 1: Metamask prompts for Skill spend approval.
After accepting that (for no good reason)...
PROBLEM 2: Metamask prompts for 0.285 BNB (the "fail" amount) and then fails even if you accept that.

**Comment by defistar** [comment]
@brian-man 

while reproducing steps:

**Step-5:**

Use market to purchase an NFT for <- your unclaimed Skill balance
PROBLEM 1: Metamask prompts for Skill spend approval.

**Unclaimed skill balance (Spending approval) is being done from :**

`await SkillToken.methods
          .approve(NFTMarket.options.address, maxPrice)
          .send(defaultCallOptions(state));`

[approve goes thru even if the SKILL balance in metamask account is 0]

**PROBLEM 2:** Metamask prompts for 0.285 BNB (the "fail" amount) and then fails even if you accept that.

This fails as the SKILL tokens are not yet claimed & Account from which Buy is triggered has SKILL balance 0.
In smart-contract: `NFTMarket.sol`

**function:**  `purchaseListing` does attempt to transfer SKILL token from wallet-account to seller &b tax-recipient

      `
        skillToken.transferFrom(msg.sender, taxRecipient, taxAmount);
        skillToken.transferFrom(
            msg.sender,
            listing.seller,
            finalPrice.sub(taxAmount)
        );
`

- This is where it gets reverted and throw Error:

`Revert reason: ERC20: transfer amount exceeds balance`

----------------------------------------------------------------------------------------

@seiyria 

- what should be the expected behaviour?

- should there be an attempt to use unclaimed SKILL tokens to buy the NFT? (in case the Wallet-Account has 0 tokens )?

- should there be a check for available SKILL balance of the msg.sender / Wallet Account?

** My apologies for delay in debugging as this is first time, that i am exploring the UserInterface and i didn't knew that i need to List the NFT before making attempt to buy in Market.

**Comment by Nizzypal** [comment]
How does one get banned from the marketplace?
![image](https://user-images.githubusercontent.com/2307123/127798609-2d16bc7e-04a4-42a4-8c27-a1e7a7e08efd.png)

**Comment by seiyria** [comment]
@Nizzypal random, tangential questions do not belong in these issues. We have a dozen github channels for this reason.

**Comment by Nizzypal** [comment]
Isee.  Where are the channels?  Im asking coz its part of my investigation.

**Comment by brian-man** [comment]
@poshdan @devinep52 @seiyria 
Do we want to allow purchasing with unclaimed skill (consuming treasury supply?)?  Or just close this out as "by design, only tokenized skill can be used to purchase from market".

**Comment by Sellie96** [comment]
Will never allow unclaimed to be used in the bazaar
