### ISSUE TITLE
Adjust market price precision

### ISSUE THREAD

**Issue by crypto-smoke** [CryptoBlades/cryptoblades#343]
Anything below 0.00 SKILL does not show up. Suggest adding dynamic precision to the displayed price. 

![image](https://user-images.githubusercontent.com/86024507/126367946-b3109cf5-a8db-4a32-898d-5f0218c9e806.png)

**Comment by bilbolPrime** [comment]
This can be a new setting but the problem will always exist.

- 3 => < 0.001 would show as 0.000
- 4 => < 0.0001 would show as 0.0000

Maybe a quick solution would be to show < 0.01 SKILL and the purchases prompting for confirmation with the actual full price?

I would take a hit at this but market doesn't work locally so that's my 2cents

**Comment by seiyria** [comment]
Another consideration is to add the real value in a tooltip if it's more precise than what's displayed

**Comment by crypto-smoke** [comment]
I figured you just use the minimum amount of precision needed:
0.01, .00005, etc. Make it dynamic.

**Comment by brian-man** [comment]
@seiyria 
Recommend `.toPrecision(8)`.
