### ISSUE TITLE
Browsing market generates bunch of errors in console

### ISSUE THREAD

**Issue by z3r0d0n3** [CryptoBlades/cryptoblades#424]
<img src="https://cdn.discordapp.com/attachments/851805599628394507/868054203736682556/unknown.png">
<img src="https://cdn.discordapp.com/attachments/851805599628394507/868054888234516480/unknown.png">

browsing market, switching pages, make this error to continuously pop up, sometimes browser is laggy with console open, maybe a return in case this.scene is null will fix this, thank you
same error with 3d assets on, and 3d assets of

**Comment by seiyria** [comment]
this _shouldnt_ happen with 3d off, since there's a straight up kill switch in the function. you have to refresh before that option change takes hold though, so keep that in mind. this error is likely some weird edge case because I haven't seen it personally. if this is the case, and turning 3d off keeps it off post-refresh, please close this

**Comment by z3r0d0n3** [comment]
3d off, browser restarted, cleaned cache, browsing market for characters, scrolling on page 2-3-4-5 and they start coming

**Comment by Sellie96** [comment]
Not valid closed.
