### ISSUE TITLE
Missing Characters in Plaza - Auto Sell?!?!

### ISSUE THREAD

**Issue by Nyawmeowww** [CryptoBlades/cryptoblades#437]
There's a user who reported that after fighting in plaza. The character that this person have, went to somebody based on the transaction hash (or something since I don't know solidity).

Transaction Hash: 0x3995d07301251020579ef78d09a9f0a9d210a0dbc5b563f05dbcc290c63e5b9b

![image](https://user-images.githubusercontent.com/31758395/126842752-1d48ac2f-b454-4e5f-9bb7-04f13f8aa994.png)

**Comment by vdaisson** [comment]
Ok, I actually took some time to take a look at this.

From his transactions, I'm pretty sure he just tried to transfer using contracts and pasted the wrong address. Then started messing things up:
![image](https://user-images.githubusercontent.com/24904012/126847446-2679f282-f0c8-481a-8f04-487a6c01dfcc.png)

He has been swapping BNB and tokens with another wallet from the start:
![image](https://user-images.githubusercontent.com/24904012/126847469-584568c2-562f-437b-9fea-4d256f5b3a12.png)
![image](https://user-images.githubusercontent.com/24904012/126847512-e2109116-cb58-4273-9419-b7a392c8a3fe.png)

Since this other wallet was lacking characters and actively playing the game, I would guess this was the wallet address where it was meant to go to.

**Comment by Nyawmeowww** [comment]
This is what the person is saying. Any thoughts?

![image](https://user-images.githubusercontent.com/31758395/126849062-8dc83d55-10e2-49f4-abcb-c8931dafbf7d.png)

**Comment by vdaisson** [comment]
His wallet claimed SKILL rewards less than 2 minutes after the supposed bugged transfer. So at least someone was using it at the time.

**Comment by Nyawmeowww** [comment]
Noted on this. Will update once I get an answer from the user.

**Comment by mvenus2** [comment]
There were more people that got hacked today. In every case their wallet claimed SKILL automatically, swapped it to bnb and sended it to the same address.
But no one of them remembered that they connected to any suspicious website or whatever
this is the address where it got sended all the time 0xf804e9e18369b09d6c497578304fdd55d844a3ee

Litterally every incoming transaction on that address is by a CB user. Always the same scheme
claim rewards -> swap to bnb -> send to 0xf804e9e18369b09d6c497578304fdd55d844a3ee

And seems like its the same address you reported.

**Comment by Nyawmeowww** [comment]
I don't know the next steps in order to report the address. Do any of you have an idea on how to report the address?

**Comment by seiyria** [comment]
Closing as this seems not related to us.
