### ISSUE TITLE
Contracts are failing after ticking the "Fight" button

### ISSUE THREAD

**Issue by Nyawmeowww** [CryptoBlades/cryptoblades#441]
At first the issue is weird, but I came into the realization that the issue requires the user to somehow click the "Fight" button on an enemy before the combat contract is triggered. This scenario ends up burning users' stamina and gas fees without any actual combat. 

Please refer to the image.
![image](https://user-images.githubusercontent.com/31758395/126855631-9c36013b-5b6c-4df2-93c5-c54eecf76bfc.png)

**Comment by bilbolPrime** [comment]
I am not sure if this is exactly what happened but a a scenario to reproduce this

1. Click fight
![image](https://user-images.githubusercontent.com/25177987/126902420-e19f8fa3-cd4e-44a9-af06-975ee902d955.png)

2. Don't fight, go plaza => combat (you select weapon again) => see enemies
3. You fight like you always do
![image](https://user-images.githubusercontent.com/25177987/126902462-2284d516-b2e4-468f-8746-721a3af995c4.png)
4. You can still confirm the first transaction resulting in

`
Error: Error: [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"message":"VM Exception while processing transaction: revert Not enough stamina!","code":-32000,"data":{"0x26b1f2e9253f36c69503db9a72b178ce1e40c957c98d6e95a60c91faa5ba4e0d":{"error":"revert","program_counter":1123,"return":"0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000134e6f7420656e6f756768207374616d696e612100000000000000000000000000","reason":"Not enough stamina!"},"stack":"RuntimeError: VM Exception while processing transaction: revert Not enough stamina!\n at Function.RuntimeError.fromResults (C:\\Program Files\\WindowsApps\\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\\app\\resources\\static\\node\\node_modules\\ganache-core\\lib\\utils\\runtimeerror.js:94:13)\n at BlockchainDouble.processBlock (C:\\Program Files\\WindowsApps\\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\\app\\resources\\static\\node\\node_modules\\ganache-core\\lib\\blockchain_double.js:627:24)\n at runMicrotasks (<anonymous>)\n at processTicksAndRejections (internal/process/task_queues.js:93:5)","name":"RuntimeError"}}}}'`

It's plausible that something like this happened and the fight (the one that was processed) was lost (though not necessarily) and the user due to bad internet or not noticing hit the confirm button again. Can we check the history of that player's battles? if right before this transaction there was a battle.

Perhaps some enhancement to not allow opening multiple fight requests would resolve this. I have no clue if it is possible though so will leave that to the core devs.

**Comment by Nyawmeowww** [comment]
The issue here is that even if the transaction failed. It burned the player's stamina.

**Comment by Ranmoac** [comment]
I just had the same issue for two fights just today, apparantly it creates a successful and a failed transactions in tandem based on my Metamask activity history

Tandem1:
    Successful: 0xb3d52bc7a5a434701e8661c7b8963019aad7ef30b607de86d4310c58ec948a2b
    Failed: 0x61357fdf7bf2274e8bbd7794720e87a4cf3ac4f0a2ce4d286bef34de4312b63c

Tandem2:
  Successful: 0xfc9ff5380d9947adfe73f35386ddf71e47d15b8aab5cb99465cf275cb3c1d348
  Failed: 0xb7e5d59a03a1713cee54fe93df536b39f5dc513765ff8aa2ab494bfc326c0700


![image](https://user-images.githubusercontent.com/88252330/127751372-cf579f2d-00fb-4160-93c3-525f076e98f4.png)

**Comment by Nyawmeowww** [comment]
Hi @Ranmoac , this space is used by devs to track everything. We are doing our best to resolve them as fast as possible. However, if you have encountered the spill on creating issue. It is indicated that users should post their feedbacks and suggestions on cryptoblades.hellonext.co

**Comment by c0nstructer** [comment]
Issue persist, even without stamina problem

`Error: Error: [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"message":"VM Exception while processing transaction: revert","code":-32000,"data":{"0x8e52d6b56ba86cf108daea1112cfc4852b77ac209ff63b3381c366fb123c3c23":{"error":"revert","program_counter":889,"return":"0x"},"stack":"RuntimeError: VM Exception while processing transaction: revert\n at Function.RuntimeError.fromResults (/Applications/Ganache.app/Contents/Resources/static/node/node_modules/ganache-core/lib/utils/runtimeerror.js:94:13)\n at BlockchainDouble.processBlock (/Applications/Ganache.app/Contents/Resources/static/node/node_modules/ganache-core/lib/blockchain_double.js:627:24)\n at runMicrotasks (<anonymous>)\n at processTicksAndRejections (internal/process/task_queues.js:93:5)","name":"RuntimeError"}}}}'`
