### ISSUE TITLE
improve xp claim flow

### ISSUE THREAD

**Issue by seiyria** [CryptoBlades/cryptoblades#462]
https://cryptoblades.hellonext.co/b/Suggestions/p/more-intuitive-xp-reward-claim-bar

**Comment by vdaisson** [comment]
How about this?

![image](https://user-images.githubusercontent.com/24904012/127136686-1b7764f1-6d28-4338-a984-ba5c315483db.png)

We don't change xp claim flow, but significantly reduce time spent by the user trying to do math.
Since we are using earnings calculator component to show current character's next milestone anyway, we could display the remaining XP to hit it.
Then, all the player has to do is compare if XP to be claimed is equal or higher than that.

It's kinda finished already. Proceed?

**Comment by seiyria** [comment]
I like this.

**Comment by newb23** [comment]
What is the current status on this and the underlying PR?

**Comment by brian-man** [comment]
> What is the current status on this and the underlying PR?

Bump.
@seiyria ?

**Comment by seiyria** [comment]
No work has been done, so nothing has changed I would guess.

**Comment by brian-man** [comment]
@vdaisson Are you interested in evolving from the original PR (or starting fresh) to move this forward?

**Comment by Sellie96** [comment]
Not valid. New UI issue
