### ISSUE TITLE
character burn / reforge

### ISSUE THREAD

**Issue by seiyria** [CryptoBlades/cryptoblades#492]
Characters will get a "rebirth level". You can buy characters from the market and burn them to buff one of your characters. This will require:

- [ ] a new "rebirth level" being tracked on the NFT. this will go up by the level of the character burnt. So if I burn a level 5 character onto my level 15 character, it will get a new stat for rebirth, set to 5. If not set, it will buff.
- [ ] solidity work to allow you to burn people from the market, and people in your party if so chosen (similar to character reforge)
- [ ] frontend work to allow you to burn a character instead of buy it, as well as to burn a character in your party to buff another one.
- [ ] solidity work to multiply the "rebirth level" by 3 when adding power to the characters combat score

This score will apply only to PvP and raids.

**Comment by aquahamzah** [comment]
What is the decided max "rebirth level" we want this to go to? if i burn a level 51 e.g - that will provide 51 rebirth.

**Comment by seiyria** [comment]
There is no max. The bonus value will be tuned based on what we see, but 3 is a good place to start.

**Comment by poshdan** [comment]
Is this a "flat" power bonus or something that gets multiplied by weapons?
A character's starting stamina is enough to get it to level 9 almost, i think a lot of people will be trying to exhaust the stamina before burning, it would only cost them ~0.0041 BNB to do the fights, so it's almost a no brainer to get 9x the benefit.

**Comment by seiyria** [comment]
@poshdan flat power bonus. I'm comfortable tiering it too, so `level / 10` is the boost. Then you only get +1 for burning a level 1-9, but +2 at 10.

**Comment by poshdan** [comment]
Yeah the tiering could help, but i think a lot of peple will still get 10-11 for the double benefit, since its not far off 9.

Right now minting a character costs like $23, I could easily see some users investing several characters worth of burns, and whales might do up to a hundred, at least in the near future.
I presume the mechanic is intended as a sink primarily for low level characters, so i guess we don't have to do anything special on burning high levels, even though they take exponentially longer to level up.

A level 51 with an awesome 5 star sword and LB could be reaching 37k power,
A level 41 with good weapon and LB might be around 20k power.
An average joe with a level 21 and decent sword would be maybe 11k.

Should the level tier bonus still apply to this (lv 51 being 6x, so 3 power per burnpoint is actually 18)? I think it's a nice balance between letting a newcomer get a head start vs rewarding long term play.

We need to figure out some power percentages that would make this worthwhile for everyone.

Spitballing here for an example, if a whale invests $2.3k in characters (100 burn) and uses them at level 11 for the double benefit, that's 3600 power on a level 51 character (3 * 2 * 100 * 6) , or about 9.7% power increase compared to the above figure, which is decent.
However, if some other person invested $200 in 9 characters, and used it on a level 41, that's only 270 power, which feels low (1.35% power increase).
I guess it's not too crazy to suggest a 2k investment should yield more, and so should a 200 one. But I want to be very careful in scaling up earning potential. Also a reminder, we cannot exceed 16.7 million power at the far end (including element bonuses etc). A lvl 255 with perfect 5 sword could get to 450k power, based on our current system.

**Comment by seiyria** [comment]
Sure. I think we can stick with a +3 per burn level and we can change that multiplier later if need be.

**Comment by brian-man** [comment]
I'll claim it as its similar to dust and I find it interesting.

**Comment by brian-man** [comment]
How do you feel about calling this Quickening instead of "rebirth level"?

I think it's kind of cool and also nostalgic. :)
https://discord.com/channels/833038505626173481/869938055149142017/870015815867588698

**Comment by brian-man** [comment]
When burning directly from market, can I use my in-game skill?  I would love to do this instead of forging weapons. (Or are we worried about the conversion of in-game skill [buyer] to token skill [seller]?)

**Comment by gofmist00** [comment]
Wow thank you for considering my suggestion in early tester chat I did not know that you really are going to make it happen. I am so happy and excited to see this in the upcoming updates.

**Comment by brian-man** [comment]
> Wow thank you for considering my suggestion in early tester chat I did not know that you really are going to make it happen. I am so happy and excited to see this in the upcoming updates.

Many of us were suggesting various flavors of this general idea. :)  I'm looking forward to thinning out the NFTMarket of the seemingly endless supply of L1 characters.

**Comment by Jivian01** [comment]
Other than market is there other sources for characters to burn?
And are we able to store bought characters in a "tavern" style secondary storage other than the main party?

As to buying characters in market is it possible to gachafy the system? % chance to recruite special character for limited time promoting people to spend more skill to recruite said chanced special character. Since we are gonna need characters to burn anyway might as well recruitement with excitement?

**Comment by seiyria** [comment]
In the future, perhaps we can have some sort of reserve army that you can buy to and burn from. 

I would like to have traited and starred characters eventually. We're just not there yet.

**Comment by WAYN-Games** [comment]
Hi, Burning characters to get fixed bonuses in power seems to make little difference in the long run. Like state previously having a high base power and getting a +3 power per 10 lvl burned is not motivating enoutgh to burn the character IMO. Economically speaking we are lossing an income source to improve another one but the improved income is nower near what is "lost" from the additionnal character.


Merging the 2 XP pool of the character might be a better option in my opinion (maybe with a deminishing factor for tweaking.
Let's say you have 2 character with 100 xp and 200 xp the resulting "boost" would be like 250 xp. So 50% of bunred XP goes to the boosted character.

**Comment by jag2us** [comment]
suggestion about character burn:
burning any level character to buff the level of specific character.
for instance, level 10 character total experience gathered to enhance a level 31.
enhancing the rewards of high tier level would compensate the burn. 
ex. if 2 level 31 character would gain 0.15 skills combined then burning/combining it to 1 character would make it a level 45 that makes 0.12 skills would be a great deal looking forward in this update.

**Comment by nrubdis** [comment]
Suggestion: Since we are using 1-5stars in weapon maybe we could also apply it to the characters instead of only adding "burnlv * 3". The bonus increment of burning character should be equal to 1star-5star weapon characteristics. In the future development, we can use the (number of stars 1-5) to group/bracket players in PVP/Dungeons/other events

**Comment by brian-man** [comment]
Assigning to @kcper since my PRs got aborted and he's been working on a different direction. :|

**Comment by brian-man** [comment]
@kcper Is this still relevant? Or is it obsolete now (and should be closed?)?
@seiyria
