### ISSUE TITLE
getRandomSeed(address user) in randoms need to have restricted access

### ISSUE THREAD

**Issue by poshdan** [CryptoBlades/cryptoblades#530]
There's no good reason why we should allow runtime lookups publicly to this function.
(ChainlinkRandoms.sol / IRandoms.sol)

It's an external view with no actual restrictions on who can pass what address in the parameter.
It would be best to whitelist certain contracts of ours. Even if it's readable through other means, it adds considerable overhead to anyone attempting to abuse it.

**Comment by poshdan** [comment]
@raymond-h we probably should add a nonce, perhaps one that modulates based on the previous random accessor's address so they don't have an entire block's lifespan to work out the result in advance.

**Comment by Nizzypal** [comment]
Does this function's legitimate calls only be made by the  owner?

**Comment by Nizzypal** [comment]
If I understood the problem (and statements) correctly, this should be solved by getting the addresses of  the contracts that are expected to call it,,, and just checking the msg.sender if its in that list.  
However my initial research about access restriction this specific involves the creation of two contracts, which makes me think my solution above might not be correct since it seems to be very simple in comparison.

**Comment by Nizzypal** [comment]
sorry misclick

**Comment by brian-man** [comment]
@Nizzypal Are you actively working on this one? If so, please "assign yourself" in the top right. Thanks!

**Comment by seiyria** [comment]
@brian-man if it's unclaimed and there's no movement/PR (like here), feel free to take it.

**Comment by DEntwickler** [comment]
https://github.com/CryptoBlades/cryptoblades/commit/85963975869e9c2818cdadbaf5872db8e2a649b8
can somebody explain to me, how could this work? its not random anymore?

**Comment by seiyria** [comment]
@DEntwickler if you would like an explanation, github is not the place to do it.
