### ISSUE TITLE
x10 Reforge Bug

### ISSUE THREAD

**Issue by Nyawmeowww** [CryptoBlades/cryptoblades#583]
Receiving an "insufficient funds error" during x10 forge but x1 seems to work.

![image](https://user-images.githubusercontent.com/31758395/128090902-964821a7-1329-46c6-96c7-745fc48b9eef.png)

To replicate the issue. 
Forge x1  in prod -> confirm all transactions -> forge x10 which will open another "Approve skill pop-up" -> then a metamask pop-up will indicate "Insufficient funds" even if you have enough funds.

**Comment by Nyawmeowww** [comment]
Based on my initial investigation, the x1 seems to be using a different skill approval compared to x10. Since, this is the case I think x10 and x1 follows 2 different paths of gas computation.

**Comment by Nyawmeowww** [comment]
> Based on my initial investigation, the x1 seems to be using a different skill approval compared to x10. Since, this is the case I think x10 and x1 follows 2 different paths of gas computation.

Prior to this, it seems to be prioritizing "unclaimed rewards" rather than the current "withdrawable skill" balance both x1 and x10 forging.

**Comment by bilbolPrime** [comment]
I tried to reproduce this locally. Only ran into #591 which is a different issue.

x10 forge costs a lot more gas than x1 due to the nature of the function (0.0159 vs 0.002 to me right now).

I think both use the same approval method. I see some usdToSkill on contract and multiplying by 10 on frontend so maybe some rounding or fluctuation.

If you are capable of reproducing this again can you please share an output of your console? the exceptions thrown would be of great help.

**Comment by OPPandaDeFi** [comment]
I was able to reproduce this locally with using a constant block time. You could also reproduce it by submitting the allowance transaction for 1x weapon and not confirming the mintWeapon transaction. Then wait for the forge buttons to come back and starting the 10x forge process. 

This was based on KRs thought that the allowance was getting calculated on the front end for the 10x after the 1x transaction allowance was already mined, but before the mintWeapon 1x transaction was mined. 

I made a fix for it by reworking the timing of when the forge buttons are reenabled. Will be pushing a PR for review here shortly.
