### ISSUE TITLE
add button to reroll enemies for combat

### ISSUE THREAD

**Issue by seiyria** [CryptoBlades/cryptoblades#597]
the button should cost 20% of what they'd earn from a win (for however many battles they can do with their current stamina)

**Comment by WAYN-Games** [comment]
Hello, I wanted to take a look at this ticket to chanlange myslef and who knows maybe contribute to the project ;).

From what I can see it seems that right now the targets are defined all at once and the randomization is based on "fixed" parameters.

My questions are : 
1) Since all targets are defined at once, should the reroll enemy function reroll all 4 targets or just the one selected ?
2) You say the option should cost 20% of what the player would earn from a win : if the reroll affect all 4 target, what should be the base cost used the average of the 4 figths in case of winn ?

**Comment by seiyria** [comment]
@WAYN-Games:

1. Reroll all characters
2. The reroll cost is based on how much stamina they have left, and how much they would win based on that number of wins. So if they have 160 stamina left, the cost should be `wonSkill * 4 * 0.2`

**Comment by WAYN-Games** [comment]
@seiyria Hello, thanks for the clarification.
For the wonSkill however, I'm still confused. There are 4 enemies, each with different power level so a different winSkill reward.
Should we take the average or on another basis ?

**Comment by seiyria** [comment]
@WAYN-Games the average is sufficient, yeah.

**Comment by WAYN-Games** [comment]
OK here is what I got so far.

Cryptoblade contract : 

- Add a method to compute the skill cost of rerolling target.
- Add a mapping to store an increment used in the target computation (increment is uinque per taget set).
- Change the target computation to use the increment.
- Added a function to update the increment for a target set.

Combat.vue :
- Added a button under the "choose weapon" to reroll target and display the cost of doing so.

What remains to be done : 
- Implement the payement/approval logic in the rerollTargets function of the contract and call it when clicking the new button
- Refesh the rerollTargetsCost after every target set change.
- Delete entries from the mapping when they become obsolete.

I did those changes in a branch but I can't publish it.
Even if it's not complete I would have liked to share this first bit to make sure I 'm going i nthe rigth/expected direction.

@seiyria Can I get write access to publish that branch or should I proceeed otherwise ?

**Comment by seiyria** [comment]
@WAYN-Games you should fork and open a PR from your fork. Also I have no idea about the gas issue. If you followed the readme you should have followed the step to up the gas limit. So I'd guess you have a contract error.

**Comment by WAYN-Games** [comment]
@seiyria 

I don't get it. I feel like the actual issue is not with the code but with the total contract size.

I forked the project and tried to reimplement things one at a time until I end up with the run out of gas error.

My contract worked before updating from main. The forked contract without modification works. 
As soon as I reimplement part of the functionality I had I run into the out of gas issue.

I striped down the function to get the reroll cost and I do soemthing realy dumb like return a constant it works, but as soon as I  have too much character in my function it fails with out of gas.

This works :
```
    function computeRerollTargetsCost(uint256 char, uint256 wep) public view returns (uint256) {
        return usdToSkill(getTokenGainForFight(getMonsterPower( getTargets(char, wep)[0]),1)) ;
    }	
```

This does not :

```
    function computeRerollTargetsCost(uint256 char, uint256 wep) public view returns (uint256) {
	uint32[4] memory targets = getTargets(char, wep);
        int128 rerollCost = getTokenGainForFight(getMonsterPower(targets[0]),1);
        return usdToSkill(rerollCost) ;
    }	
```

If it is so, someone with more experience on the project should probably refactor the cryptoblade.sol contract to extract all function related to  weapon (mintWeaponN) and character (mintCharacter) to their respective contracts or to the blacksmith contract (reforgeWeapon). 

This would shrink the cryptoblade contract size and make it handle only core gameplay (fights).

I'll stop working on that for now.

**Comment by WAYN-Games** [comment]
Nevermind, it seems my suggestion was patially applied in the latest update, I resynched my  fork and the contract is smaller now.
There are still stuff that could be moved to other contract like getMyCharacters or getMyWeapons.

Also isUnlikely does not seem to be used anywhere.

My changes now get deployed so I'll keep pushing forward after all.

**Comment by brian-man** [comment]
@seiyria It looks like the linked PR was closed (in favor of smoke bomb).  Should this be closed as well?

**Comment by seiyria** [comment]
If there's a smoke bomb issue then yeah this can be closed
