### ISSUE TITLE
integrate ads on the cryptoblades site

### ISSUE THREAD

**Issue by generomuga** [CryptoBlades/cryptoblades#641]
It is possible to integrate like Admob or any ads API. Let's maximize the number of user visits on the page and make profits from it. Any thoughts?

**Comment by Nyawmeowww** [comment]
Hi. The idea is great and we appreciate it. However, please refrain from posting here if you're not a dev because this is used for tracking issues and features. Instead, I recommend you post it on cryptoblades.hellonext.co. We check it every Monday. Thanks!

Also, the ISSUE TEMPLATE should have explained everything. When you pressed **"New Issue"**


# ISSUE TEMPLATE
IF YOU ARE A USER, DO NOT OPEN ISSUES AGAINST THIS REPOSITORY. OPEN THE ISSUE ON HELLONEXT INSTEAD: https://cryptoblades.hellonext.co/

PLEASE DELETE THIS AND THE ABOVE TEXT BEFORE OPENING AN ISSUE
