### ISSUE TITLE
NaN in price for sell dialog

### ISSUE THREAD

**Issue by seiyria** [CryptoBlades/cryptoblades#665]
![image](https://user-images.githubusercontent.com/763609/129369228-f67a5708-73bd-4632-9243-5de9ddf4017d.png)

**Comment by kevinunger** [comment]
Any clue why this is happening? I encountered it as well, but can't reproduce it.

**Comment by seiyria** [comment]
So far, no, all I know is that it's happening unfortunately.

**Comment by kevinunger** [comment]
Ok, I'll will try to fix it this weekend or at least pin down the cause.

**Comment by KennyUTN** [comment]
The problem is the activeListingMarketTax() method on Market.vue ( line 1725, and called on line 482+-)

To reproduce the bug, list any of your weapons, then go to the blacksmith and click on any of your weapons. after that go back to the market and search for your listed weapon. When you click change price and type any number. the bug will occur.

The change price modal that pops is not properly getting the value of activeListingMarketTax(), or it is getting it as null, hence the NaN afterwards and the "extra % market fee" (should be 'extra 10% market fee').

The bug does not occur if you are on the market and before attempting to change a price you try to list a weapon of yours, If you do so, then activeListingMarketTax() gets called before and everything works.

**Comment by kevinunger** [comment]
Thanks for the detailed description @KennyUTN! The bug does occur like you are saying, but it's also occurring when:  refreshing the site and changing tabs. Basically, the bug occurs anytime if you don't come from the 'List NFTs' tab, because when clicking the 'List NFTs' tab loadMarketTaxes() is called. That's the only time when this.weaponMarketTax is set. I suggest that we call the function, when switching to the 'Search NFTs' tab. This fixes the bug.
