### ISSUE TITLE
DMCA & C&D TODO

### ISSUE THREAD

**Issue by seiyria** [CryptoBlades/cryptoblades#740]
There needs to be a DMCA and C&D sent to the hosts of the following projects:

- folk warriors (https://folkwarriorsgame.io)
- blade knight (https://bladeknight.io)
- polyblades (https://game.polyblades.io)
- bunicorn (https://bunicorn.game)

these should be sent to (where applicable):

- the host for the frontend
- the host for the backend
- the gitbook (if they cloned ours)
- the home page (if they cloned ours)

_please reach out before doing this so only one person is doing it)

DMCA how to: https://www.ipwatchdog.com/2009/07/06/sample-dmca-take-down-letter/id=4501/

C&D how to (potentially): https://www.rocketlawyer.com/business-and-contracts/intellectual-property/copyrights/document/cease-and-desist-letter

**Comment by hollow736** [comment]
fuck you pleb

**Comment by hollow736** [comment]
it's defi, dmca your mom :)

**Comment by kevinunger** [comment]
If someone wants to report:

folk warriors (https://folkwarriorsgame.io)
- host frontend/backend (folkwarriorsgame.io / api.folkwarriorsgame.io): 
https://porkbun.com 
abuse@porkbun.com
Porkbun hosts on OVH 

blade knight 
- host frontend/backend (bladeknight.io / hard-coded market? ): 
www.namecheap.com
abuse@namecheap.com
Namecheap uses AWS

polyblades.io
- host frontend/backend (game.polyblades.io / ? ): 
www.namecheap.com
abuse@namecheap.com
Namecheap uses AWS

bunicorn.game
- host frontend/backend (bunicorn.game / api.bunicorn.game ): 
_Cloudflare_

**Comment by seiyria** [comment]
@kevinunger I explicitly said you _can't_ go after the domain hosts, you have to go after the frontend/backend host. In this case, you would go to OVH for folk warriors, namecheap for BK, and digitalocean for game.polyblades, and cloudflare for bunicorn. You _cannot_ go to porkbun for FW and namecheap for polyblades.

**Comment by kevinunger** [comment]
@seiyria Ok, got it. Updatet my comment

**Comment by macguyversmusic** [comment]
help me understand as im a little new to git.  these projects copied the OPEN SOURCE and are running their own versions of this game?  is it now closed???

What terms are breached by them please for clarity 
can you show me clauses from the licence that are provably broken?  evidence??

is this illegal? 

because i joined github specifically to do this and i would hate for a bunch of people with nothing better to do to come annoying me in a year because the most they ever contributed was a complaint and i missed some small print and forgot to rename a function from yourFunction to Myfunction.

are or are not open source projects on github free to use and copy and cut snippets from?

or did you just want to put the URLS somewhere that people could see them????  maybe these posts are troll posts to get focus on these sites

Presumably you hope nobody will see these URLS nor go and invest money or play these games now that you exposed these URLS?

possibly you don't care that unsuspecting users already involved in these games may lose their lives savings if something they have invested their life savings in gets pulled.

open source?  help me understand.  

so how do crypto blades users benefit from these takedown notices?

how will these notices help the cryptoblades gamers??? people with money still in SKILL.

We look forward to your open and candid response!

**Comment by seiyria** [comment]
@macguyversmusic you are clearly neither a legal expert nor a licensing expert.

You need to go learn about software licensing, as well as what not having a license means. [Here is a link for your reading pleasure](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository).

However, I'll include the relevant part that I've repeated ad infinitum that people don't seem to understand:

![image](https://user-images.githubusercontent.com/763609/134399040-db4e3ad9-2024-4ea1-8039-ffb4e1e7c59f.png)

Do not come back without understanding what this means.

**Comment by macguyversmusic** [comment]
You have in my opinion, irresponsibly posted urls that in turn will probably lead to some poor fool losing money that they would never have lost without your posting the links.  REVIEW THAT - SEND YOUR NOTICES BUT DO NOT ADVERTISE THESE URLS.

i merely would like to understand what these platforms did that breached a licence. in order that when the moment comes, and i release something that may or may not contain snippets of open source code from github, i do not come under the same problem and can licence and credit my work correctly.

as a side note this will be the last communication on this since i find "you need to X" and "don't come back without....." a little toxic and completely off the point.  i dont even know why the response above was sent as it clearly answers no part of the initial querey and is simply a defensive rant.   

I'm sure it doesn't matter to you that some poorer people may lose a few hundred dollars for your irresponsible advertising of these URLS but it matters to me and my associates who have had to listen to countless people beg for help to recover funds from scams - AND YOU POSTED ALL SCAM LINKS by your own admission.

the questions were: 


1.What terms are breached by them please for clarity
2. Can you show us clauses from the licence that are provably broken? evidence?? 
3.Is this illegal? 
4.How do crypto blades users benefit from these takedown notices?
5.How will these notices help the cryptoblades gamers??? people with money still in SKILL.

your response so far which has not been helpful in any way:


     "(@macguyversmusic you are clearly neither a legal expert nor a licensing expert.) "


although we will not communicate further we would still be delighted to see the answers to these questions by the person with the expertise who made the post so that we can understand and make sure we behave appropriately and within guidelines here on github.

**Comment by seiyria** [comment]
One to look out for: https://battlefish.site/

![image](https://user-images.githubusercontent.com/763609/134433380-35c52336-c367-4fe3-9f44-a96dbdf82507.png)


I'm guessing they won't be revamping as much as they claim.

**Comment by Sellie96** [comment]
folk warriors
+
blade knight
+
polyblades.io
+
bunicorn.game

Have been issued DMCA's on their respective hosts.

Battlefish hasn't released yet but I've got one ready for when they do should they not be unique.

**Comment by seiyria** [comment]
@Sellie96 Thank you so much. We can close this and move it to bounty if you're interested. I'm going to pin it and track further developments.

**Comment by Sellie96** [comment]
Will do. I'll keep you all updated with any progress only ones to confirm they will be taking action is CloudFare so far.

**Comment by CamYuan** [comment]
I know this was already closed, but is there a link to their codebases of these projects?

If not publicly available, how do we know they copied the code here?

Sorry if this was discussed in the discord already

**Comment by seiyria** [comment]
@CamYuan Looking at their frontend is sufficient. If not, looking at things such as their DOM structure, their API response (if any), etc is also sufficient. Additionally, some of these codebases _are_ on github, but given that there is no real person behind them, github restored their codebases, so it's fairly easy to see that they've done this.

**Comment by jagergab** [comment]
I think you better work on paying the players their hard-earned SKILLS instead of chasing after other NFT projects who seem to be more popular, successful, and not as fishy as what you guys are doing. Holding the investors' money hostage for months and not be able to come up with a viable solution to the crisis is what you should answer. You're basically trying to drag others down with your failure. Own it and be responsible instead..or should I say... MAN UP

**Comment by seiyria** [comment]
@jagergab get off of the internet if your reading comprehension is so abysmal that you can't read the thread.
