### ISSUE TITLE
NFT Bridge

### ISSUE THREAD

**Issue by bilbolPrime** [CryptoBlades/cryptoblades#781]
Create an NFT bridge that allows a player to transfer an NFT from chain A to chain B.

1. Player adds an NFT to a "storage".
      - NFT is still owned by player but cannot be used in game unless taken out.
2. Player requests an NFT to be transferred to another chain.
      - Item is now tagged as "pending transfer" and can no longer be withdrawn unless player cancels the request.
      - Request cannot be canceled if the item is picked up by bot and transfered.
3. Bot picks up items pending transfer and creates an entity mirroring the stats of the NFT.
      - This includes LBs, cosmetics, renames etc... + original id
      - Bot updates the transfer request to "done" and sets a reference id that represents the "entity" at the new chain.
4. Player can check the status of his transfer request from storage in original chain (pending, done) and in the new chain (available).
5. Once available. Player can convert the "entity" into NFT and related data is updated (cosmetics, renames ...).
      - A ref id is created representing chain and original id.
      - When bridging, if you bridge ID BSC189 to HECO, it will mint with BSC189 so the id represents both heritage and uniqueness.
      - Frontend to use ref id as seed for names / images when present

Limitations:
- Each player can (initially) only transfer 5 items per wallet per day to keep things in check

Basic structure for a transfer request:
  - Target NFT ID
  - NFT Type
  - Target Chain
  - Status (pending, done)
  - Reference id in new chain

**Comment by bilbolPrime** [comment]
Basic storage implemented + basic support for bridge bot

**Comment by bilbolPrime** [comment]
Pushed basic implementation for character and weapon bridging

- Bot gives player NFT data
- Player mints guaranteed stats

Still needs polishing and preserving cosmetics / renames + optimization and code clean up

**Comment by bilbolPrime** [comment]
@kevinunger 
Please note that you need to hardcode the address now, it has been removed from blacksmith per request from @poshdan 

Some changes still need to be made but for frontend this should be operational:

**Storage:**

- getStorageItemIds(tokenAddress) => returns ids of owned NFT of that type
- storeItem(tokenAddress, id) => store NFT id of that type
- withdrawFromStorage(tokenAddress, id) => withdraw NFT id of that type

**Bridge:**

- chainBridgeEnabled(chainId) => is chain enabled to transfer to
- bridgeItem(tokenAddress, id, targetChain) => request to bridge an NFT to target chain. Only one request at a time.
- cancelBridge() => cancel any active request; can only be done if not transfered by bot yet.
- getBridgeTransfer() => get bridge request of player (to show status)
- getReceivedNFTs() => returns list of bridgedItemIds that were received on chain
- getReceivedNFT(bridgedItemId) => returns data of item pending extraction from bridge.
- withdrawFromBridge(receivedNFTId) => extract the item from the bridge (goes to storage)
- getNFTChainId(nftAddress, nftId) => get the refChainId of an nft. Globally unique accross all chains and reflects parent chain / nft id.

Will probably add some more functions as enhancements but that should be enough to get everything done from front end

**Comment by kevinunger** [comment]
Current Frontend for moving NFTs into Storage and requesting bridging:
Bridge View added to the options menu
![image](https://user-images.githubusercontent.com/5601589/136700819-d4b8da4c-adf3-4610-8620-dbb3f750e6de.png)

User can move Weapons/Chars from Inventory to Storage
![image](https://user-images.githubusercontent.com/5601589/136700787-f6b7c935-d0a8-44ab-9f54-08784725161d.png)

User can request transfer to a selected chain or move Weapons/Chars back to inventory
![image](https://user-images.githubusercontent.com/5601589/136700893-845c2a89-17c3-408e-8d92-f9cd09ed2496.png)

User can view status of the transfer and cancel the transfer, if the status is still pending
![image](https://user-images.githubusercontent.com/5601589/136700938-08fdc08d-ed39-415a-aeaa-3127c3a1e96a.png)




I added 2 env vars to .env.* 
VUE_APP_STORAGE_CONTRACT_ADDRESS=""
VUE_APP_NETWORK="test" //or "production" (added because chainIds differ between mainnet/testnet)

**Comment by kevinunger** [comment]
Changed withdraw UI
![image](https://user-images.githubusercontent.com/5601589/137226198-71c646b6-9887-40ec-bed1-0fcb328f21e0.png)
